### ISSUE TITLE
The bot automatically cancels the download

### ISSUE THREAD

**Issue by trancanh1102** [gautamajay52/TorrentLeech-Gdrive#107]
I use a bot to download many files and about 1-2 hours the bot will automatically cancel the download.
Is that an error?
How to fix the error?
Thanks for watching my problem
![Capture](https://user-images.githubusercontent.com/40576239/90328446-a69c4800-dfc6-11ea-98bb-f1db0d4c4f81.PNG)

**Comment by gautamajay52** [comment]
> I use a bot to download many files and about 1-2 hours the bot will automatically cancel the download.
> Is that an error?
> How to fix the error?
> Thanks for watching my problem
> ![Capture](https://user-images.githubusercontent.com/40576239/90328446-a69c4800-dfc6-11ea-98bb-f1db0d4c4f81.PNG)

Can I see the logs?🤔😐

**Comment by gautamajay52** [comment]
Fixed🥱
