### ISSUE TITLE
__Init__.py has  AUTH_CHANNEL ID  appended ? 

### ISSUE THREAD

**Issue by sevvian** [gautamajay52/TorrentLeech-Gdrive#110]
Hi @gautamajay52  ,

Is there any reason why AUTH channel has been appended with this value  by default in the __init__.py file in the code.
I was going through the code to see if where rclone has been triggered, but stumbled upon this line of code, which looks like  left by someone ?

AUTH_CHANNEL.append(539295917)   ?

do you recognize this, is it fine to have some unrecognized auth channel has been embedded in the code ?

**Comment by gautamajay52** [comment]
That's me only😬

Sometimes some people used to come to me and asked if my bot is running or not... without logs.

So to debug the bot only I have kept my id there, If I can start the bot...means that is working.

No worry 😐
