### ISSUE TITLE
Can't find the 'DESTINATION_FOLDER' 

### ISSUE THREAD

**Issue by KAMG95** [gautamajay52/TorrentLeech-Gdrive#114]
I tried the Name of my shared drive and the ID of the drive and the link of the drive with no result all I get is 
"https://drive.google.com/folderview?id=" I don't know what to write in DESTINATION_FOLDER value!!

**Comment by gautamajay52** [comment]
While writing or deploying...you should read the description 🤒

Btw there u should fill the name of folder where you wanted to upload the file in gdrive😶

**Comment by KAMG95** [comment]
> 
> 
> While writing or deploying...you should read the description 🤒
> 
MY BAD I discovered this to late....Now it works fine you are a life saver BRO♥
