### ISSUE TITLE
Authorization Not works Properly

### ISSUE THREAD

**Issue by iamlordutkarsh** [gautamajay52/TorrentLeech-Gdrive#115]
Any user can cancel anyone's File !

**Comment by gautamajay52** [comment]
Yes...if u are using `/cancel GID`; but with button, only owner or the person who has given command to download 😶

**Comment by iamlordutkarsh** [comment]
hmmm, plox change this ! Allow only user who added torrent or file to cancel

**Comment by gautamajay52** [comment]
> hmmm, plox change this ! Allow only user who added torrent or file to cancel

That's code are from base repo.
And I don't wanted to touch those code.😑

But if you want...you can edit the GID part from code🤒🙄

**Comment by iamlordutkarsh** [comment]
Lemme check , I also want to contribute !
