### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by rockydares** [gautamajay52/TorrentLeech-Gdrive#118]
Can you include apk files download from apkpure?
It would be helpful. Here I found something from this repository:
[0x27/apkpure_get](https://github.com/0x27/apkpure_get)

**Comment by gautamajay52** [comment]
Sorry, but this is not the moto of this repository.

**Comment by Harsh-br0** [comment]
> [0x27/apkpure_get](https://github.com/0x27/apkpure_get)
Good repo , but its not maintained , i saw its last commit
