### ISSUE TITLE
Cant restart the torrent download after cancelled it

### ISSUE THREAD

**Issue by telegrambotdev** [gautamajay52/TorrentLeech-Gdrive#130]
i cancelled a torrent leeching and tried to restart the torrent leeching.its stuck at showing `trying to downl9ad` and then it will turned to

`can't get metadata 

#stopped`

like this.the same torrent,successfully started leeching before.restarting the bot will help to resolve this problem.

so fix it or add a command to restart the bot,thank you :)

![IMG_20200824_154652_081](https://user-images.githubusercontent.com/20116017/91033491-12169300-e621-11ea-8912-3710701e6ec1.jpg)
![IMG_20200824_154640_165](https://user-images.githubusercontent.com/20116017/91033511-1a6ece00-e621-11ea-889e-dbd8f2e12c81.jpg)

**Comment by gautamajay52** [comment]
I have checked that...it works😶

**Comment by telegrambotdev** [comment]
> I have checked that...it works😶

but not for me,thats why i screenshotted the error.if you can add a bot restart command too.That will be very helpful

**Comment by gautamajay52** [comment]
> > I have checked that...it works😶
> 
> but not for me,thats why i screenshotted the error.if you can add a bot restart command too.That will be very helpful

I can add restart command...but that will only work for heroku🤒

**Comment by telegrambotdev** [comment]
> > > I have checked that...it works😶
> > 
> > 
> > but not for me,thats why i screenshotted the error.if you can add a bot restart command too.That will be very helpful
> 
> I can add restart command...but that will only work for heroku🤒

😢😢😢 i am hosting this on my server. there is a restart command on lyzzis bot.can you check it ?

**Comment by telegrambotdev** [comment]
> > > I have checked that...it works😶
> > 
> > 
> > but not for me,thats why i screenshotted the error.if you can add a bot restart command too.That will be very helpful
> 
> I can add restart command...but that will only work for heroku🤒

https://github.com/lzzy12/python-aria-mirror-bot

check this.there is a /restart  command on their code and working fine on my server too.
restart command is very helpful bro

**Comment by gautamajay52** [comment]
I didn't know that😕
Will look there 😬

**Comment by telegrambotdev** [comment]
check `line 39`

https://github.com/lzzy12/python-aria-mirror-bot/blob/master/bot/__main__.py

**Comment by telegrambotdev** [comment]
> I didn't know that😕
> Will look there 😬

https://github.com/gautamajay52/TorrentLeech-Gdrive/issues/130#issuecomment-679240295




> > > > I have checked that...it works😶
> > > 
> > > 
> > > but not for me,thats why i screenshotted the error.if you can add a bot restart command too.That will be very helpful
> > 
> > 
> > I can add restart command...but that will only work for heroku🤒
> 
> https://github.com/lzzy12/python-aria-mirror-bot
> 
> check this.there is a `/restart` command on their code and working fine on my server too.
> `restart` command is very helpful bro

take a look here LI NE 39

https://github.com/lzzy12/python-aria-mirror-bot/blob/master/bot/__main__.py

**Comment by telegrambotdev** [comment]
Any updates ? because i am still having the same error after i forked your recent update.if you can add,a restart command bro


![IMG_20200825_145006_721](https://user-images.githubusercontent.com/20116017/91157064-7cdbd300-e6e2-11ea-9234-0d2f4ef76014.jpg)
![IMG_20200825_145011_257](https://user-images.githubusercontent.com/20116017/91157067-7f3e2d00-e6e2-11ea-80d0-3cf0773b6d9c.jpg)

**Comment by gautamajay52** [comment]
For now use /renewme command to clear the storage.
If this type of things happens.

**Comment by telegrambotdev** [comment]
> For now use /renewme command to clear the storage.
> If this type of things happens.
> 
> But it will clear all your downloads...so better try if there is no any other process running.🙃

Not helped.Only restart the bot can solve this issue.


![IMG_20200825_193930_833](https://user-images.githubusercontent.com/20116017/91184888-ca6c3600-e70a-11ea-83e3-891023908f04.jpg)

**Comment by telegrambotdev** [comment]
![IMG_20200825_194233_497](https://user-images.githubusercontent.com/20116017/91185212-28008280-e70b-11ea-90fb-4103431adb8b.jpg)

**Comment by gautamajay52** [comment]
This(infohash already registered) problem should be fixed after updating bot to latest code.

If not, reopen the issue again.
