### ISSUE TITLE
Deploy on Heroku Issues

### ISSUE THREAD

**Issue by NEOIR** [gautamajay52/TorrentLeech-Gdrive#131]
Hi

Im fork this Repo ( My fork url is : https://github.com/NEOIR/TorrentLeech-Gdrive ) 
Then Rename app.jso to app.json
Then Click on Deploy on Heroku and Set All Enviroment Required Value

![image](https://user-images.githubusercontent.com/53754407/91034349-2014e580-e61a-11ea-84e4-d1ee1a42e70f.png)

But my Bot is Not Work

Thanks for Support.

**Comment by gautamajay52** [comment]
Go to resources section and turn on the dyno🧐

**Comment by NEOIR** [comment]
Dyno is Turend on 

![image](https://user-images.githubusercontent.com/53754407/91034923-0627d280-e61b-11ea-853d-a8a9cf59d907.png)

**Comment by gautamajay52** [comment]
Logs?

**Comment by NEOIR** [comment]
> Logs?

![image](https://user-images.githubusercontent.com/53754407/91036098-f957ae80-e61b-11ea-9948-aab46b4e51c8.png)

**Comment by gautamajay52** [comment]
Your bot is working🙄
Reply to /leech to the link

**Comment by NEOIR** [comment]
Thanks You Bro
