### ISSUE TITLE
Deploy on CPanel PYthon 

### ISSUE THREAD

**Issue by NEOIR** [gautamajay52/TorrentLeech-Gdrive#132]
Hi

I Purchased A CPanel With this feature Can Run Any Python, Node and Ruby Scripts .

Provider Documention For Python Promgramers Url : https://docs.planethoster.com/guide/panneaux-de-controle/world-panel/world-panel-infos-additionnelles/langages-python

![image](https://user-images.githubusercontent.com/53754407/91040999-7850e500-e624-11ea-886c-e98032511775.png)

Can I Run Your Repo in This ?

**Comment by gautamajay52** [comment]
I don't know, what's cPanel?🙄

**Comment by NEOIR** [comment]
> I don't know, what's cPanel?🙄

cPanel is an online Linux-based graphical interface (GUI) used as a control panel to simplify website and server management. cPanel allows you to publish websites, manage domains, organize web files, create email accounts, and more.

And I Can Run any Python, Node and Ruby Scripts .
And I Access to SSH Server

**Comment by gautamajay52** [comment]
But I can't access 😬
As I don't have any...so I can't test and say anything about that😕

**Comment by NEOIR** [comment]
In Shared Hosting Its Imposible .

Thank U
