### ISSUE TITLE
Recommendation and Questions

### ISSUE THREAD

**Issue by NEOIR** [gautamajay52/TorrentLeech-Gdrive#138]
Hi 

## Recommendatin
Please Add Option to index local file ( Download file in heroku ) and Size .

## Questions
I can't leech any Torrent or magnet link .
Show Metadata and File Leeching Data but there always is 0% and don't change .
Where is problem ?

- Magnet and Torrent link have 800 Seeders but Doesn't leech .

and Please Tell me What is Value for "INDEX_LINK" Key in config Vars

Thank You ❤️

**Comment by NEOIR** [comment]
## Recommendation
Please add Option in Config to set file owner .

Now When Upload File to telegram with /leech Command, in Detail Uploaded File Owner of file set to Robot ( Name, Username and ID ).
Please add Option to set this my username or anything

Thanks.

**Comment by NEOIR** [comment]
No Any Help or Answer ?

**Comment by gautamajay52** [comment]
For INDEX_LINK u have to make index of your gdrive.

**Comment by NEOIR** [comment]
@gautamajay52 Thanks For Answer .

and Other Question ?

**Comment by gautamajay52** [comment]
Your Problem-- I can't do anything about that 
and Recommendation...I don't know about them😑
