### ISSUE TITLE
How to change streamble to normal file

### ISSUE THREAD

**Issue by vaisakhc56** [gautamajay52/TorrentLeech-Gdrive#144]

**Comment by gautamajay52** [comment]
What do you mean by normal file?

**Comment by vaisakhc56** [comment]
![Screenshot_2020-08-27-13-10-31-285_org telegram plus](https://user-images.githubusercontent.com/64364212/91411977-b9d0d280-e866-11ea-8131-a9047869d480.jpg)

**Comment by gautamajay52** [comment]
Try setting `UPLOAD_AS_DOC` as `True` in heroku vars.
And if you got your required normal file.🥱

Then you good to go.🚶🚶

**Comment by vaisakhc56** [comment]
Thanks bro

**Comment by vaisakhc56** [comment]
Thumbnail not working on doc

**Comment by gautamajay52** [comment]
> Thumbnail not working on doc

Fixed at [b143f6a9d6](https://github.com/gautamajay52/TorrentLeech-Gdrive/commit/b143f6a9d613c368ad823d100f48a3c514875579)

**Comment by vaisakhc56** [comment]
it's work
