### ISSUE TITLE
CHANGING PYTDL TO DOWNLOAD PLAYLIST AS MP3 FILES

### ISSUE THREAD

**Issue by noonegupta734** [gautamajay52/TorrentLeech-Gdrive#147]
Will Changing this bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 to this bestaudio[ext=m4a]/mp3 download playlist as mp3 ?

**Comment by gautamajay52** [comment]
You can try and check....but I will add this feature in future🚶

**Comment by noonegupta734** [comment]
It downloads file as webm not as mp3 It tried many different possibilities
but it does not work😢😢😞 and it always downloads as webm

**Comment by gautamajay52** [comment]
So trying without reading docs is baseless.😬
Better read the readme section in youtube-dl.
And figure out yourself....they have explained everything properly there🧐

**Comment by noonegupta734** [comment]
Ok Sir I'll try
