### ISSUE TITLE
Thumbnail not working on doc

### ISSUE THREAD

**Issue by vaisakhc56** [gautamajay52/TorrentLeech-Gdrive#148]

**Comment by gautamajay52** [comment]
There is No thumbnail for doc😶

**Comment by vaisakhc56** [comment]
![Screenshot_2020-08-28-14-56-26-502_org telegram plus](https://user-images.githubusercontent.com/64364212/91545464-b577e880-e93e-11ea-80e7-811d847e10fb.jpg)

**Comment by vaisakhc56** [comment]
How to do in publileech repo upload doc like file

**Comment by gautamajay52** [comment]
Fixed at [b143f6a9d6](https://github.com/gautamajay52/TorrentLeech-Gdrive/commit/b143f6a9d613c368ad823d100f48a3c514875579)
