### ISSUE TITLE
SOME LINKS NOT UPLOADING AFTER REACHING 100% (NO URI AVAILABLE)

### ISSUE THREAD

**Issue by RomanGoddess** [gautamajay52/TorrentLeech-Gdrive#149]
below is a screenshot of error i get when leeching from direct links

![Screenshot_20200828_123121](https://user-images.githubusercontent.com/53878781/91556384-8788a900-e92a-11ea-832c-38d9859eed0c.jpg)

**Comment by gautamajay52** [comment]
Tap the save button and send log as .txt format.

Or u can get log by sending /log to your bot.

These small ss is not helping much.🧐

**Comment by RomanGoddess** [comment]
[Torrentleech-Gdrive.log](https://github.com/gautamajay52/TorrentLeech-Gdrive/files/5141868/Torrentleech-Gdrive.log)

**Comment by RomanGoddess** [comment]
Link To The File, You May Try Also

http://62.210.142.219:8000/direct.php?data=xgO54OVIGqgRqNheF4b7cSNApt5f047Rl7GC2UF4gixDrLgSg2WlBJ9yNrLc7hyuz4nRZkLiCdmdlkp09alWd05RVNeNRX11RkBd6R9KPPmXbZDoaa9S5sSg31xAdReUO2cFboCekAmJYuC52KsvJ383U8XfXM9rBYhHdV9n%2BDwK5d8AtWMlMAb5AXjtqVIhIHOBIT1eJKV0IKDKbnqGAKm5yCFrlON%2BMuQ9OS7zUwRCXiy0AvPcr4bcyMEjB5bFujpnbbVB7O8tEBlf36AoGCfWPfNft2Q2GJj%2B3ehQ7vbKeh76F5yc24WKK3ImPeMz2QDnyPCNp8kskwVn4o5KIRcyoxHthWlGNV%2Fy%2FHNHOTiXdhOkQGJ6%2FRnprCkN2gqrjzHYYb1dAyYopTOodmICKqyF%2FKzqlhoQ6Lfsqo86Q1cwzyJGzd6JX1bjzHrYfc92RF3%2FiC7pbkR4HdyFAm7hKA%3D%3D

**Comment by gautamajay52** [comment]
Blame your link.
As it is not giving proper information about its file.
It's size (shows as aria has allocated size of)1.5GB...but it is only sending 1.39GB of file.

U can check /status from bot it shows 99.08% only

**Comment by RomanGoddess** [comment]
You're indeed right. Thanks for the information
