### ISSUE TITLE
 No Custome rename on gleech

### ISSUE THREAD

**Issue by theRay1s** [gautamajay52/TorrentLeech-Gdrive#151]
Add some filter or something 

So files don't get renamed while gleech 
Or add this specialy for Zip files 

So that zip files don't get renamed while gleech 

Please this is must

**Comment by gautamajay52** [comment]
What do you mean?🧐
Explain with some examples.😑

**Comment by theRay1s** [comment]
@gautamajay52 u added the custom filename feature 
I'm talking about it 

So I want is that remove custom filename from gleech command

**Comment by gautamajay52** [comment]
Come to telegram support group and chat!!
You can find  link in Readme section.😶

This is not an issue/bug related to bot.🙄

So closing it😑
