### ISSUE TITLE
How to register commands having space in between like /gleech archive?

### ISSUE THREAD

**Issue by askfriends** [gautamajay52/TorrentLeech-Gdrive#154]
hi..

i am registering commands in @BotFather and when i register "/gleech archive" it doesn't save it and gives error "Sorry, the list of commands is invalid. Please use this format:" 

So how can i register all those commands having two words and space in between?

Thanks

**Comment by gautamajay52** [comment]
No you can't...but I will change the documentation in future. 😬

After that you can add those commnads in @Botfather. 😶

**Comment by X-Gorn** [comment]
(For now) before gautam change the doc

Add only gleech, after you did it then go to heroku and set GLEECH_COMMAND = gleech@usernamebot (your bot username)
And you can do with
/gleech@usernamebot archive
It will works

**Comment by askfriends** [comment]
> No you can't...but I will change the documentation in future. 😬
> 
> After that you can add those commnads in @Botfather. 😶

Thanks..
can't you remove space and use like "gleecharchive" or "gleech-archive" ?

**Comment by askfriends** [comment]
> (For now) before gautam change the doc
> 
> Add only gleech, after you did it then go to heroku and set GLEECH_COMMAND = gleech@usernamebot (your bot username)
> And you can do with
> /gleech@usernamebot archive
> It will works

Thanks for the input..
but /gleech@usernamebot archive also have space , will botfather register it?

normally all commands work well,  i just want to save commands for easy access in my bot

**Comment by gautamajay52** [comment]
Done
