### ISSUE TITLE
How to fix this

### ISSUE THREAD

**Issue by vaisakhc56** [gautamajay52/TorrentLeech-Gdrive#174]
![IMG_20200909_172749](https://user-images.githubusercontent.com/64364212/92595339-d555c780-f2c1-11ea-964a-765df0177f6a.jpg)
How to fix bro

**Comment by LuqmanReburn** [comment]
use VPS

**Comment by vaisakhc56** [comment]
Use have any suggestion which vps

**Comment by LuqmanReburn** [comment]
I'm using OVH Cloud VPS
