### ISSUE TITLE
Getting malicious file warning for some files,so i cant download them using gindex

### ISSUE THREAD

**Issue by telegrambotdev** [gautamajay52/TorrentLeech-Gdrive#177]
![IMG_20200911_210924_147](https://user-images.githubusercontent.com/20116017/92946185-eba38500-f473-11ea-8876-7ca8ed380735.jpg)

when i tried to download the uploaded torrent files, gindex throws this error. are this because of gindex problem ? i can download them using direct gdrive url. 
so any solutions ?

**Comment by gautamajay52** [comment]
What you want?
I am not able to understand 🥺

**Comment by telegrambotdev** [comment]
> What do you want?
> I am not able to understand 🥺

ok.let me explain.i tried to download a cracked software.its downloaded and uploaded to gdrive.then i access the index url,it shows like this

**Comment by telegrambotdev** [comment]
> What do you want?
> I am not able to understand 🥺

check this

https://github.com/rclone/rclone/issues/2338

**Comment by telegrambotdev** [comment]
https://github.com/prasmussen/gdrive/issues/234

**Comment by gautamajay52** [comment]
You should open this issue to gdindex repo.
May be they can add `--drive-acknowledge-abuse` like something as rclone.😬

**Comment by telegrambotdev** [comment]
Ok bro thanks
