### ISSUE TITLE
Does it supports zip too ?

### ISSUE THREAD

**Issue by telegrambotdev** [gautamajay52/TorrentLeech-Gdrive#18]
like /gleech zip
/gleech rar

please add those too

**Comment by gautamajay52** [comment]
No...

**Comment by telegrambotdev** [comment]
lol every body needs that.if we try to download a big pc game file .and it contains 30 files ? we have to download 1 by one ?

**Comment by gautamajay52** [comment]
> lol every body needs that.if we try to download a big pc game file .and it contains morethan 30 files ? we have to download 1 by one ? so kindly add atleast one zip funcition to gleech.

lol there is already one which can be triggered by `/gleech archive`
So u can try that.🙄🤗

**Comment by telegrambotdev** [comment]
Thanks bro :)
