### ISSUE TITLE
Getting a new error after i updated your repo

### ISSUE THREAD

**Issue by telegrambotdev** [gautamajay52/TorrentLeech-Gdrive#189]
Getting the below error while i am trying to leech. can you please help me to fix this ? telegram leeching is ok,error is occuring while torrent and direct link leeching,may be problem is in aria

`<=' not supported between instances of 'str' and 'int`

**Comment by telegrambotdev** [comment]
`26-Sep-20 00:51:44 - tobrot.helper_funcs.download_aria_p_n - INFO - '<=' not supported between instances of 'str' and 'int'
26-Sep-20 00:51:44 - tobrot.helper_funcs.download_aria_p_n - INFO - '<=' not supported between instances of 'str' and 'int'
26-Sep-20 00:51:45 - tobrot.helper_funcs.download_aria_p_n - INFO -`

**Comment by MaxxRider2** [comment]
WTF 🙄

**Comment by telegrambotdev** [comment]
![IMG_20200926_074430_226](https://user-images.githubusercontent.com/20116017/94328374-a9c82200-ffcf-11ea-88f2-94910f35b6d2.jpg)
![IMG_20200926_074425_650](https://user-images.githubusercontent.com/20116017/94328376-af256c80-ffcf-11ea-840c-5a66a2effa7f.jpg)
