### ISSUE TITLE
sometimes /gleech downloads the files but not uploading to google drive

### ISSUE THREAD

**Issue by Ashfanndm** [gautamajay52/TorrentLeech-Gdrive#191]
**/gleech** downloads the files but not uploading to google drive and it stuck. but if you look the torrent file in **/status** command its there, downloading. but once the download is compleated it is not uploading to google drive.  and is there any way to access the link of the file from vps. (cached link)

**Comment by gautamajay52** [comment]
Use /exec to access.
And you can also Upload to gdrive by using that.

So at first read how rclone works

**Comment by Ashfanndm** [comment]
**/exec** does not works. should I reply to any previous messages or I should type anything after the **/exec** command

**Comment by gautamajay52** [comment]
This is not related to bot issue.

So I am closing this.😕

For further help, ask in help group...you can get link from Readme 🐈🐈
