### ISSUE TITLE
Multiple bot in a group

### ISSUE THREAD

**Issue by devsdocs** [gautamajay52/TorrentLeech-Gdrive#196]
Hi,
Before starting, thank you for amazing project you did and credit to others contributor also.

I'm hosting this repo on multiple VPS and want to add multiple bots in a single group. This is related to command to input in BotFather.

1. I'm searching for modifying "/renewme" and "/getsize" command. Can I just input the value in config.py file?

2. To input the value in config.py, does it have to be in integer (in quotes) or any other format?

Here some reference picture, sorry for bad handwritting 🙏

![Screenshot_20201112-182106_Samsung Notes](https://user-images.githubusercontent.com/73208025/98921297-78ba9700-2514-11eb-8d4d-83aa3e43e4b6.jpg)

**Comment by gautamajay52** [comment]
I have to add those custom commands...I will add today 😶

**Comment by gautamajay52** [comment]
Done, Now you can check the readme for the required commands.

**Comment by devsdocs** [comment]
Thank you 🙏
