### ISSUE TITLE
Ytdl Is Broken Even After The Update

### ISSUE THREAD

**Issue by FristyFlakes** [gautamajay52/TorrentLeech-Gdrive#197]
Youtube Links Aren't Working After The Update You Made 8 Days Ago Please Verify On Your Side, Thanks

**Comment by gautamajay52** [comment]
It is working on my side.
Can you send logs after /log just after giving /ytdl commands??😶

**Comment by FristyFlakes** [comment]
![Screenshot_20201125_141156](https://user-images.githubusercontent.com/71187213/100232114-389de000-2f28-11eb-9910-57056aee23dd.jpg)

**Comment by FristyFlakes** [comment]
Here is a test link 

http://www.youtube.com/watch?v=47YClVMlthI

**Comment by gautamajay52** [comment]
Worked for me 😶

**Comment by gautamajay52** [comment]
> Here is a test link
> 
> http://www.youtube.com/watch?v=47YClVMlthI

In your case ERROR is video unavailable means may be your link is incorrect. Can you try  with another valid links and report again???

**Comment by FristyFlakes** [comment]
Link is very much valid 

http://www.youtube.com/watch?v=1lQtoRFaLsA
http://www.youtube.com/watch?v=JC2yu2a9sHk
http://www.youtube.com/watch?v=DK_0jXPuIr0

Another examples of links not working.

**Comment by gautamajay52** [comment]
> Link is very much valid
> 
> http://www.youtube.com/watch?v=1lQtoRFaLsA
> http://www.youtube.com/watch?v=JC2yu2a9sHk
> http://www.youtube.com/watch?v=DK_0jXPuIr0
> 
> Another examples of links not working.

Every link is working for me.
Can you check the version of youtube-dl by command 
` /exec youtube-dl version` and post here????

**Comment by FristyFlakes** [comment]
> > Link is very much valid
> > http://www.youtube.com/watch?v=1lQtoRFaLsA
> > http://www.youtube.com/watch?v=JC2yu2a9sHk
> > http://www.youtube.com/watch?v=DK_0jXPuIr0
> > Another examples of links not working.
> 
> Every link is working for me.
> Can you check the version of youtube-dl by command
> ` /exec youtube-dl --version` and post here????


![Screenshot_20201125_143632](https://user-images.githubusercontent.com/71187213/100234630-a566a980-2f2b-11eb-89b2-7eb624f64c0f.jpg)

**Comment by gautamajay52** [comment]
Oh!
May be video is unavailable for your server location.

There is only few links not working for you or every youtube link ????

**Comment by FristyFlakes** [comment]
Only Few Links Not Working.. Others works

**Comment by gautamajay52** [comment]
Then that's your vps location problem 🤒
So, I am closing this issue, If your problem persists you can reopen again.
