### ISSUE TITLE
can't stop /gleech

### ISSUE THREAD

**Issue by 547555909** [gautamajay52/TorrentLeech-Gdrive#198]
can't stop /gleech sometimes

**Comment by gautamajay52** [comment]
Downloading or uploading ? 😶

**Comment by 547555909** [comment]
> Downloading or uploading ? 😶

Downloading.Sometimes when i click the cancle button,it seems not work

**Comment by 547555909** [comment]
the bot will reply "checking..?"

**Comment by gautamajay52** [comment]
Use `/cancel GID`
You can get GID value from progress message.

**Comment by 547555909** [comment]
> Use `/cancel GID`
> You can get GID value from progress message.

Ok,thank you
