### ISSUE TITLE
/status command show all history downloads

### ISSUE THREAD

**Issue by 547555909** [gautamajay52/TorrentLeech-Gdrive#201]
Can this command only show downloading task?

**Comment by telegrambotdev** [comment]
yup..just show only downloading tasks..now its showing the whole history

**Comment by gautamajay52** [comment]
It will show your whole history of downloading, completed along with stopped due to some error.

**Comment by 547555909** [comment]
> It will show your whole history of downloading, completed along with stopped due to some error.

We hope this command just show only downloading tasks。

Now the bot send me a status flie，and the file is becoming more and more larger.

**Comment by gautamajay52** [comment]
Done
