### ISSUE TITLE
When downloading a large files, the download status is not updated

### ISSUE THREAD

**Issue by 547555909** [gautamajay52/TorrentLeech-Gdrive#202]
When the download time has passed, the download status is not updated

**Comment by 547555909** [comment]
![Uploading Snipaste_2020-12-04_19-17-42.png…]()

**Comment by KGK06** [comment]
Better To Join @GBotStoreSupport In Telegram 🤗🤗

**Comment by gautamajay52** [comment]
> When the download time has passed, the download status is not updated

May be because of flood wait by telegram message.edit
Tips: Increase Sleep time

**Comment by 547555909** [comment]
> > When the download time has passed, the download status is not updated
> 
> May be because of flood wait by telegram message.edit
> Tips: Increase Sleep time

Emmm，how can i do for Increase Sleep time?

**Comment by gautamajay52** [comment]
Update your bot to latest.
I have added the code to handle the flood error.

To increase Sleep time...read readme, there is a variable for that.

**Comment by 547555909** [comment]
> Update your bot to latest.
> I have added the code to handle the flood error.
> 
> To increase Sleep time...read readme, there is a variable for that.

Thank you so much！
