### ISSUE TITLE
(Request) Adding built in alias for in-group command

### ISSUE THREAD

**Issue by devsdocs** [gautamajay52/TorrentLeech-Gdrive#203]
The app does not detect **in-group** bot commands, as telegram by default add "@mybotname" right after each commands.

Just asking a simple favor to add built in function besides custom commands, like entering /gleech@mybotname in-group equal to /gleech, so the bot can understand, thank you!

**Comment by gautamajay52** [comment]
I didn't get you.

**Comment by devsdocs** [comment]
Simply the bot need to understand that /gclone@mybotname = /gclone

**Comment by gautamajay52** [comment]
That's why there is custom commands.
It helps people to use more than one bots in same group.

**Comment by devsdocs** [comment]
Yes I understand it.

This is just not about custom commands, idea to exclude "@mybotname" to be entered after each custom commands.

When we need to give command in group, we can manually type "/gleech", but whe pressing command button "/" and long press the command from the list, it automatically add "@mybotname" after each command. Just and idea request, not critical though.

Thank you.
