### ISSUE TITLE
Task is download completed but it not upload

### ISSUE THREAD

**Issue by 547555909** [gautamajay52/TorrentLeech-Gdrive#206]
When i us /status command,i find the task "CSI.Crime.Scene.Investigation.S06.720p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv] "is download completed,like this picure:
<img width="972" alt="Snipaste_2020-12-10_10-31-13" src="https://user-images.githubusercontent.com/19320063/101713808-5a27cb80-3ad3-11eb-959d-17e475768e27.png">
Then i enter the docker container,i find the file "CSI.Crime.Scene.Investigation.S06.720p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv] " is not upload.
<img width="1396" alt="Snipaste_2020-12-10_10-30-36" src="https://user-images.githubusercontent.com/19320063/101713972-a3781b00-3ad3-11eb-96bd-ae46241fd9ab.png">

**Comment by gautamajay52** [comment]
But the torrent is still in active state.

**Comment by gautamajay52** [comment]
And also don't forget to update your app to latest code.

**Comment by 547555909** [comment]
> May be some error has happened. See the status of that by `/exec aria2p show` if you see complete then it should.
> 
> And also send log.

<img width="1093" alt="Snipaste_2020-12-10_11-16-02" src="https://user-images.githubusercontent.com/19320063/101716851-1cc63c80-3ad9-11eb-88ef-95fd3fe66cc5.png">
I am sure my app is the lastest code

**Comment by gautamajay52** [comment]
You can see error there means some error has happened while down-loading.

See the for update, check repo if you are at latest or not. I have updated yesterday too.

**Comment by 547555909** [comment]
> You can see error there means some error has happened while down-loading.
> 
> See the for update, check repo if you are at latest or not. I have updated yesterday too.

emmm,i just update yesterday,i was refork your repo yesterday,and rebuild docker images

**Comment by gautamajay52** [comment]
if you are using vps...just run `git pull`

**Comment by 547555909** [comment]
> if you are using vps...just run `git pull`

yes,i am using vps,but i used on docker. is docker images no need to rebuild?

**Comment by gautamajay52** [comment]
Yes...for sure

**Comment by 547555909** [comment]
> Yes...for sure

ok

**Comment by 547555909** [comment]
dose the docker container need rebuild?
