### ISSUE TITLE
/ytdl download youtube video failed

### ISSUE THREAD

**Issue by 547555909** [gautamajay52/TorrentLeech-Gdrive#208]
/ytdl https://youtu.be/ra7sFQrKjO0
<img width="441" alt="Snipaste_2020-12-11_10-50-59" src="https://user-images.githubusercontent.com/19320063/101855690-d0ddcb00-3b9e-11eb-98eb-f3576ec84f44.png">

**Comment by gautamajay52** [comment]
Read readme how to use this repo.
