### ISSUE TITLE
ENV VAR for split algoritm 

### ISSUE THREAD

**Issue by telegrambotdev** [gautamajay52/TorrentLeech-Gdrive#216]
![IMG_20201231_220015_674](https://user-images.githubusercontent.com/20116017/103418186-9a9ad680-4bb3-11eb-8029-289df53a6d7a.jpg)

can you add an ENV VAR for split algoritm for splitting files in rar format. you can check that on spechides repo

Thank you

**Comment by gautamajay52** [comment]
Benefits?😞

**Comment by telegrambotdev** [comment]
> Benefits?😞

we can easily extract huge size uploaded telegram files easily..now bigger files are splitting in an older format(hjsplit).so thats hard to join together,but spechide added rar feature for splitting on his new release..thats awsome..so please add this feature.

check   https://t.me/ThankTelegram/803398

**Comment by telegrambotdev** [comment]
![IMG_20201231_221746_081](https://user-images.githubusercontent.com/20116017/103418745-08480200-4bb6-11eb-8740-22facfe3852f.jpg)

he implemented rar feature instead of this and thats super is easy to join files.
