### ISSUE TITLE
Wrong INDEX link getting after /gleech archive command

### ISSUE THREAD

**Issue by telegrambotdev** [gautamajay52/TorrentLeech-Gdrive#22]
We will get a wrong google drive index link after 
`/gleech archive` command.i am getting correct index links for `/gleech` command.the problem lies on `/gleech archive` command.

the file is getting like     test.tar.gz
when i changed that url to  test.tar ..then it worked.
also when i archived a long named torrent and i got the wrong index link.(its archived without fullname)

so check these issues

**Comment by telegrambotdev** [comment]
got the reason for the2nd pbm

i am getting the archived link like

https://testing.workers.dev/Dark%20(2020)%20English%20S03%20Complete%20720p%20NF%20WEB-DL%20-%202.4%20GB%20.tar.gz


its not the full url.the actual url must look like

https://testing.workers.dev/Dark%20(2020)%20English%20S03%20Complete%20720p%20NF%20WEB-DL%20-%202.4%20GB%20-%20DD-%205.1%20MSub%20x264%20-%20Shadow%20(BonsaiHD).tar

so the .gz must removed at the end and we have to get the full file name.tar..this will solve the problem

**Comment by gautamajay52** [comment]
> got the reason for the2nd pbm(long named torrent)
> 
> i am getting the archived link like
> 
> https://testing.workers.dev/Dark%20(2020)%20English%20S03%20Complete%20720p%20NF%20WEB-DL%20-%202.4%20GB%20.tar.gz
> 
> its not the full url.the actual url must look like
> 
> https://testing.workers.dev/Dark%20(2020)%20English%20S03%20Complete%20720p%20NF%20WEB-DL%20-%202.4%20GB%20-%20DD-%205.1%20MSub%20x264%20-%20Shadow%20(BonsaiHD).tar
> 
> so the .gz must be removed from the end and we have to get the full file name.tar at the end of url..this will solve the problem

🤔

**Comment by telegrambotdev** [comment]
worked.
