### ISSUE TITLE
Cancel of a leech doesn't delete partly downloaded files

### ISSUE THREAD

**Issue by em108** [gautamajay52/TorrentLeech-Gdrive#23]
Hello, I deployed the bot on a vps and noticed that if you cancel a /gleech download for a reason where there may be few seeds or any other reason, the party leeched files remain on the server rather than being deleted. Could there be a way they could be automatically deleted rather than logging onto the server to delete them?

**Comment by gautamajay52** [comment]
> Hello, I deployed the bot on a vps and noticed that if you cancel a /gleech download for a reason where there may be few seeds or any other reason, the party leeched files remain on the server rather than being deleted. Could there be a way they could be automatically deleted rather than logging onto the server to delete them?

are u using /cancel command or leech got cancelled by its own???

**Comment by em108** [comment]
> are u using /cancel command or leech got cancelled by its own???

I'm using the /cancel command it brings at the bottom of the download. I'll redeploy the bot again to check if the problem was on my end and see.

**Comment by em108** [comment]
UPDATE: I switched to the 'easy way' of deploying the bot. 
Also thanks so much for the bot development 😀
