### ISSUE TITLE
heroku?

### ISSUE THREAD

**Issue by IshwaranRudhara** [gautamajay52/TorrentLeech-Gdrive#233]
any hint to run on heroku ???

**Comment by askfriends** [comment]
+1

**Comment by IshwaranRudhara** [comment]
+1

**Comment by Mrvishal2k2** [comment]
@gautamajay52 when closing this ?😐😎

**Comment by askfriends** [comment]
> @gautamajay52 when closing this issue?😐😎

:P

**Comment by IshwaranRudhara** [comment]
> @gautamajay52 when closing this issue?

i only got the acces to close

**Comment by Mrvishal2k2** [comment]
> > @gautamajay52 when closing this issue?
> 
> i only got the acces to close

Then do close ...
You know heroku is still a question mark and never gets solved 😂
So why this issue sir...
