### ISSUE TITLE
Deploy To Heroku Button not working

### ISSUE THREAD

**Issue by kamalteja1998** [gautamajay52/TorrentLeech-Gdrive#25]

**Comment by gautamajay52** [comment]
working for me🤔🙊
Try in desktop mode or in desktop 🙄

**Comment by AdzeB** [comment]
Not working for me also

**Comment by Gwenstephanie** [comment]
Working perfectly here use https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fgautamajay52%2FTorrentLeech-Gdrive&template=https%3A%2F%2Fgithub.com%2Fgautamajay52%2FTorrentLeech-Gdrive

**Comment by gautamajay52** [comment]
You all have to fork the repo and then tap on deploy to heroku button.

**Comment by gautamajay52** [comment]
So I am closing it!!
