### ISSUE TITLE
Always returning 1st config as Default

### ISSUE THREAD

**Issue by sobuj53** [gautamajay52/TorrentLeech-Gdrive#258]
Say I have 3, (namely 1,2,3) config in `rclone.conf` and default is 1 . Now I change the active config to 2 using `/rclone` command. now When I call again `/rclone` command bot will say 1 is my default config even though I've just changed it to 2 ! So I was just wondering wouldn't it be informative to display the active default config which is now 2 , when we call `/rclone` command instead of just returning the 1st config name from `rclone.conf`
 fyi [L35](https://github.com/gautamajay52/TorrentLeech-Gdrive/blob/d8cd49eebd4671c35d5607a2c86d52ff8de8ba41/tobrot/plugins/choose_rclone_config.py#L35)

**Comment by gautamajay52** [comment]
It is working properly. Only thing is that it should say the name of the default config. I will fix.
