### ISSUE TITLE
Button Link Not Work

### ISSUE THREAD

**Issue by Kidzdev** [gautamajay52/TorrentLeech-Gdrive#26]
![Screenshot_20200629-063628](https://user-images.githubusercontent.com/34876175/85963079-3f0e4700-b9de-11ea-8c29-d10a180a4154.jpg)

**Comment by gautamajay52** [comment]
Have u set index link?

**Comment by gautamajay52** [comment]
send log in support group.

**Comment by gautamajay52** [comment]
Fixed!!!🤐
