### ISSUE TITLE
Rclone config on vps

### ISSUE THREAD

**Issue by rockydares** [gautamajay52/TorrentLeech-Gdrive#46]
You've given tutorials for herokuapp but where can I add those RCLONE variables to my remote server config (config.py)?
![IMG_20200710_204623](https://user-images.githubusercontent.com/66517282/87170050-750cce80-c2ee-11ea-93e0-45c52bd5e4f9.jpg)

**Comment by gautamajay52** [comment]
I don't understand what u want!?
Explain a bit😬

**Comment by rockydares** [comment]
How to configure RCLONE config? 

type = drive
scope = drive
token = {"access_token":xxxxxxxx}
team_drive = xxxxxxxxxxx

How to put them in config.py ?

**Comment by gautamajay52** [comment]
`type = drive\nscope = drive\ntoken ={"access_token":xxxxxxxx}\nteam_drive = xxxxxxxxxxx`

**Comment by nimma0001** [comment]
Getting this issue how to solve

**Comment by nimma0001** [comment]
![Screenshot_20200919-094130](https://user-images.githubusercontent.com/62383660/93658781-55b3bf80-fa5c-11ea-9bda-4f965fe5d1b5.png)
How to add this line

**Comment by nimma0001** [comment]
![Screenshot_20200919-094614](https://user-images.githubusercontent.com/62383660/93658858-0752f080-fa5d-11ea-83f0-40d12ae6033c.png)

**Comment by gautamajay52** [comment]
> Getting this issue how to solve

Hey...plz don't post confidential information on github.
U can contact me on telegram group. Links are in description.
