### ISSUE TITLE
update the highest file size

### ISSUE THREAD

**Issue by GAMERPIYUSH9090** [gautamajay52/TorrentLeech-Gdrive#47]
Plz update the highest file size from 1.5GB to 2GB as telegram has updated its terms

**Comment by GAMERPIYUSH9090** [comment]
![Screenshot_20200710-210232](https://user-images.githubusercontent.com/67828895/87171767-c6b65880-c2f0-11ea-80df-ef0fd6f38699.png)

**Comment by gautamajay52** [comment]
Its already there.🙄

**Comment by GAMERPIYUSH9090** [comment]
You Have updated it?

**Comment by GAMERPIYUSH9090** [comment]
If yes then how can i update it as i have already deployed it to heroku

**Comment by gautamajay52** [comment]
> If yes then how can i update it as i have already deployed it to heroku

Update your fork. And redeploy from heroku GiHub section by connecting your GitHub account.

**Comment by GAMERPIYUSH9090** [comment]
Ok thanks
