### ISSUE TITLE
Request about rclone integration in a repository

### ISSUE THREAD

**Issue by em108** [gautamajay52/TorrentLeech-Gdrive#51]
Hello. Is there a way this [repository](https://github.com/lzzy12/python-aria-mirror-bot)  can be modified to also support rclone in its upload module?
While it has limited features compared to the publicleech which was modified to what it is today, it would be nice if rclone would be integrated in this [one](https://github.com/lzzy12/python-aria-mirror-bot)  too.

**Comment by gautamajay52** [comment]
Why you want to add rclone there!?🧐
Give me a reason😬
That will kill the quality of that repo you mentioned.🙄

**Comment by em108** [comment]
Thanks so much for responding. I understand it would destroy most of its original functions but here are some of my reasons;
1. with rclone, you have the ability to upload to multiple storage hosts not only Google drive which I saw your repo.
2. A strange but rare occuring issue used to happen to me when uploading rather large folders and uploads get stuck in the middle with no way of resuming them. I raised this issue sometime back but till now there's no fix for it but never has there been this occurrence in an rclone upload. 
Link: https://github.com/lzzy12/python-aria-mirror-bot/issues/51

Those are some of my reasons. Thanks once again for responding :)

**Comment by gautamajay52** [comment]
Then why not this repo 🙄https://github.com/gautamajay52/TorrentLeech-Gdrive

The think you have listed is already here, so why working on other repo!?🧘

**Comment by em108** [comment]
It was because of something I faced when hosting locally on a VPS. I thought most probably the reason was that I didn't have sudo access till I tried again about 2 days ago this time with root access but faced the same thing.
It's related to something I raised sometime back whereby deletion of a torrent doesn't clean incompatible files so you have to log onto the server to manually delete.
https://github.com/gautamajay52/TorrentLeech-Gdrive/issues/23

I also faced this error while hosting locally: https://del.dog/inuwamofit.txt in the middle of a download and came to a conclusion that this wouldn't work well for someone's who's hosting locally and wants more space other than what heroku provides.

I know it's a very large request so I understand your decision either way. Thanks once again for hearing me out

**Comment by gautamajay52** [comment]
> It was because of something I faced when hosting locally on a VPS. I thought most probably the reason was that I didn't have sudo access till I tried again about 2 days ago this time with root access but faced the same thing.
> It's related to something I raised sometime back whereby deletion of a torrent doesn't clean incomplete files so you have to log onto the server to manually delete.
> #23
> 
> I also faced this error while hosting locally: https://del.dog/inuwamofit.txt in the middle of a download and came to a conclusion that this wouldn't work well for someone's who's hosting locally and wants more space other than what heroku provides.
> 
> I know it's a very large request so I understand your decision either way. Thanks once again for hearing me out

Hey, I would have helped you to deploy on vps, but unfortunately I don't have vps to test.🥺

Yeah now I know why you wanted those.🤗

But alone I can't manage all things and so I am out from adding rclone features to that repo. 

So better use this as it is by deploying to heroku or when I will get vps and test this by deploying...I will update it.

We need Dockerfile for this to be deployed on vps I guess.

**Comment by em108** [comment]
Thanks so much for understanding my impossible request and I too understand it's a very hard task to request so I won't push it any farther as it's rather time consuming to create new modifications on another repository :)

If you need a server for testing I would be glad to help you out by deploying a mini test server that you can use for some days on my GCP credits. Then you can perfect the code and carry  out tests on your own pace and I delete it when you're done. We can exchange details on telegram if interested.

Thank you once again 😄

**Comment by gautamajay52** [comment]
> Thanks so much for understanding my impossible request and I too understand it's a very hard task to request so I won't push it any farther as it's rather time consuming to create new modifications on another repository :)
> 
> If you need a server for testing I would be glad to help you out by deploying a mini test server that you can use for some days on my GCP credits. Then you can perfect the code and carry out tests on your own pace and I delete it when you're done. We can exchange details on telegram if interested.
> 
> Thank you once again

Ok you can message me t.me/gautamajay52

**Comment by em108** [comment]
Sure thing 👍
