### ISSUE TITLE
Fix Unrar didn't work

### ISSUE THREAD

**Issue by X-Gorn** [gautamajay52/TorrentLeech-Gdrive#52]
Today I've updated my bot, but when i'm trying to leech unrar, the file downloaded but not uploading, even yesterday i can unrar, please fix diz issue .. unzip work as properly btw.

**Comment by gautamajay52** [comment]
Will you plz give logs?

**Comment by gautamajay52** [comment]
Fixed😬
Now You can update your fork and redeploy.🤐

**Comment by X-Gorn** [comment]
> Today I've updated my bot, but when i'm trying to leech unrar, the file downloaded but not uploading, even yesterday i can unrar, please fix diz issue .. unzip work as properly btw.



> Will you plz give logs?
