### ISSUE TITLE
heroku time limits

### ISSUE THREAD

**Issue by GAMERPIYUSH9090** [gautamajay52/TorrentLeech-Gdrive#55]
Hey Bro,How can i deploy my telegram bot for 24/7 free of cost  heroku is having 550hrs, any tricks to efficiently utilise it???

**Comment by em108** [comment]
> Hey Bro,How can i deploy my telegram bot for 24/7 free of cost heroku is having 550hrs, any tricks to efficiently utilise it???

When you add a card to your account you get an extra 450 hours added to your account. That's all you need to do

**Comment by maiz94** [comment]
Bruh
