### ISSUE TITLE
[Feature Request] add rename option

### ISSUE THREAD

**Issue by X-Gorn** [gautamajay52/TorrentLeech-Gdrive#66]
Example:
Link| Newfilename.mp4
Then reply with any command ..

**Comment by gautamajay52** [comment]
> Example:
> Link| Newfilename.mp4
> Then reply with any command ..

Why don't you read the readme? 😬
This feature is already there. 🧘

**Comment by X-Gorn** [comment]
> > Example:
> > Link| Newfilename.mp4
> > Then reply with any command ..
> 
> Why don't you read the readme? 😬
> This feature is already there. 🧘

I need it for ytdl command.

**Comment by gautamajay52** [comment]
Will see about it in next update. 🆗

**Comment by Gwenstephanie** [comment]
Next Update Passed xD..

**Comment by gautamajay52** [comment]
May be in next update...I forgot😜😬

**Comment by skbaji6** [comment]
i created the pull request for tleech rename option. will add ytdl rename option if you are ok Gautam

**Comment by RomanGoddess** [comment]
> i created the pull request for tleech,leech,ytdl rename option. if you are ok merge the following request.Tested code.
> 
> https://github.com/gautamajay52/TorrentLeech-Gdrive/pull/101/commits

Tested and working fine.. Please merge at gautam

**Comment by gautamajay52** [comment]
#112 Done😬

**Comment by RomanGoddess** [comment]
Build failed on heroku twice

**Comment by gautamajay52** [comment]
After this commit?🤔

**Comment by gautamajay52** [comment]
> Build failed on heroku twice

Send logs...if possible 😬

**Comment by RomanGoddess** [comment]
> > Build failed on heroku twice
> 
> Send logs...if possible 😬

![IMG_20200816_202537_463](https://user-images.githubusercontent.com/53878781/90342268-addf4800-dffe-11ea-860d-61f470fd9e50.jpg)

**Comment by gautamajay52** [comment]
> > > Build failed on heroku twice
> > 
> > 
> > Send logs...if possible 😬
> 
> ![IMG_20200816_202537_463](https://user-images.githubusercontent.com/53878781/90342268-addf4800-dffe-11ea-860d-61f470fd9e50.jpg)

It is because, your beloved Botcloud youtube-dl fork/clone doesn't exist 🤦

**Comment by RomanGoddess** [comment]
I know why now... My dumb mistake

**Comment by gautamajay52** [comment]
> I know why now... My dumb mistake

Ok...then...try and report, if it is working properly or not😬

**Comment by RomanGoddess** [comment]
> > I know why now... My dumb mistake
> 
> Ok...then...try and report, if it is working properly or not😬

Working fine.. Tested and Approved :)
