### ISSUE TITLE
Downloading from vk.com links...

### ISSUE THREAD

**Issue by jgo42** [gautamajay52/TorrentLeech-Gdrive#70]
It's on YouTube DL supported site list. But when we go for downloading from vk.com links it requires login credentials. Please solve this problem in next update.

**Comment by sethazazel** [comment]
Some vk links require login if it got banned from public view. Try to open link in private session of your browser, if it says login for view it thats mean you can't download without account.

**Comment by jgo42** [comment]
That's what I was saying. I can't download it without account. Is it possible to solve this problem in next update

**Comment by UsamaKarim** [comment]
I think you should open this issue in ytdl repo first. It would be helpful for gautam
