### ISSUE TITLE
Please Hide this Repo otherwise heroku will ban it!

### ISSUE THREAD

**Issue by rafsanbasunia** [gautamajay52/TorrentLeech-Gdrive#77]

**Comment by gautamajay52** [comment]
#48 🤣

**Comment by gautamajay52** [comment]
Use it in limit... nothing will happen 🧘🤗

**Comment by usmanmughalji** [comment]
No need to hide this repo it's depend on users how they use it but better way to use it as limited and don't abuse this beautiful bot. Great work and amazing bot.

**Comment by none5969** [comment]
> Use it in limit... nothing will happen 🧘🤗

Everything has happened lol😂

**Comment by gautamajay52** [comment]
> > Use it in limit... nothing will happen 🧘🤗
> 
> Everything has happened lol😂

This is an issue tracker, so keep your talk limited to issue only.
