### ISSUE TITLE
Naming issues

### ISSUE THREAD

**Issue by Atrate** [gautamajay52/TorrentLeech-Gdrive#83]
Hey there!

I don't know if you're aware, but there exists a very large private tracker named exactly **TorrentLeech**, so this repo's name might cause confusion and mixups.

**Comment by gautamajay52** [comment]
Really?🤔
How can you explain a bit?😬

**Comment by Atrate** [comment]
https://opentrackers.org/torrentleech/

The naming isn't that important of an issue, but the first time I saw the repo I thought it was about seeding on TL through GD

**Comment by gautamajay52** [comment]
can u tell me how it is related to tracker?
means how repo name is related to tracker?🤔
btw, repo name is "TorrentLeech-Gdrive"

Me still confused😐

**Comment by Gwenstephanie** [comment]
Absolutely No Point Opening This Issue 😐
