### ISSUE TITLE
How to get bot status? and About Archive

### ISSUE THREAD

**Issue by askfriends** [gautamajay52/TorrentLeech-Gdrive#88]
i couldn't find any command to know the status of the bot, like ongoing downloads or uploads to drive.
I want to have that because sometimes download doesn't start, so its always better to know the latest status of the bot with /status command.

Also is there any option to use our preferred archive size before uploading to drive?
for example torrent file is 16gb and i want to split it 4gb each part.

**Comment by gautamajay52** [comment]
About the status of uploading and other thing that is not there is bit on complicated, but I will give a update regarding the logs of rclone process by which you can know the current status of uploading/cloning.
