### ISSUE TITLE
Bot is not showing Download Progress and gleech archive not working

### ISSUE THREAD

**Issue by askfriends** [gautamajay52/TorrentLeech-Gdrive#89]
When i add .torrents or magnet url, it only shows "Downloading status" and then nothing happens, When file is downloaded completely then it shows "file is uploaded to cloud".

So am i missing here something? why it doesnt show download progress in real time? is there any heroky vars im missing?

Also i tried a /gleech archive command for a movie which was about 3gb, but it ended up uplaoding a 3mb .tar.gz file.
So how to fix it?

![asaaa](https://user-images.githubusercontent.com/2517219/89420936-d76db900-d74c-11ea-93a3-e6ffbe411a0a.png)

![asssss](https://user-images.githubusercontent.com/2517219/89420920-d3da3200-d74c-11ea-998e-b7e3d45a96c2.png)

**Comment by gautamajay52** [comment]
I will appreciate the logs😬🙄
Issue without logs is baseless😐🚫

**Comment by askfriends** [comment]
> I will appreciate the logs😬🙄
> Issue without logs is baseless😐🚫

[tg-lch-logs-1596644252329.txt](https://github.com/gautamajay52/TorrentLeech-Gdrive/files/5029706/tg-lch-logs-1596644252329.txt)
 logs attached

**Comment by gautamajay52** [comment]
Your logs contains nothing 😐
Come to telegram group and do further reporting

**Comment by gautamajay52** [comment]
You can find those in readme

**Comment by gautamajay52** [comment]
Closing Now 😐
