### ISSUE TITLE
Dyno is missing 

### ISSUE THREAD

**Issue by Apitpr0** [gautamajay52/TorrentLeech-Gdrive#99]
For some reason the dyno out of nowhere just gone.. Even before forking the new repo... Here are some screenshot 
![IMG_20200809_052831_931](https://user-images.githubusercontent.com/58835837/89720151-c0ce9880-d9be-11ea-9428-b0b6a36ad611.jpg)
![IMG_20200809_050241_658](https://user-images.githubusercontent.com/58835837/89720156-c7f5a680-d9be-11ea-82b8-dcf03d0ec657.jpg)

**Comment by gautamajay52** [comment]
Keep some patience, it will be there soon😐
